### ISSUE TITLE
Use a unique icon

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/website-old#1]
This site uses a copy of the open data handbook. It should use a unique icon. 
I'm not sure if this icon from http://data.okfn.org/data is appropriate

![icon-128](https://cloud.githubusercontent.com/assets/9379524/14770961/8de80de2-0ac0-11e6-8fae-3afc9a85bbc3.png)

**Comment by danfowler** [comment]
Thanks for raising!  We're working on a new logo for Frictionless Data.

**Comment by roll** [comment]
FIXED
