### ISSUE TITLE
Theme for v1

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website-old#10]
- [ ] Really concerned about "invisibility" of side menu and lack of top menu
  - For handbook this style made sense as more book like but we will need a more normal top menu here I think.
- [ ] bootstrap "boxes" stuff for e.g. /tools/ and some of /guides/ - see old http://data.okfn.org/tools/ for example
  - support fancy buttons

**Comment by rufuspollock** [comment]
@smth can you take a look here?

Especially important is menu / navbar: we'd like to get standard "over the top" navbar with drop down menu items and lose the sidebar menu for this site.

/cc @jobarratt

**Comment by smth** [comment]
I haven't had a chance to discuss this project yet, so it's difficult for me to know how best to resolve any issues at present. I would guess that using the handbook theme is a stopgap, and so we should/will  implement something more appropriate.

**Comment by rufuspollock** [comment]
@smth @jobarratt indicated you had some capacity for this over the next couple of weeks and these relatively small items could go in it.

If there were a way to fix these relatively easily in this theme without too much tweaking then I would go that route rather than a full new design at this point.

**Comment by smth** [comment]
Yes, I just need to catch up with @danfowler first.

**Comment by danfowler** [comment]
@rgrp I really agree with @smth that these items are strictly for a [v2 of the site](https://github.com/frictionlessdata/frictionlessdata.io/issues/18).

**Comment by rufuspollock** [comment]
@smth @danfowler my concern is best being the enemy of the good ;-)

@smth could you please get us estimates (not when just "how much) on just doing navbar "fix" here vs work on Full v2 theme #18 (which is not yet full specified).

**Comment by roll** [comment]
@danfowler 
So we've finished with v1 and looking forward to https://github.com/frictionlessdata/frictionlessdata.io/issues/18?

**Comment by roll** [comment]
MERGED #18
