### ISSUE TITLE
Add Case Study "Call to Action"

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#100]
Once a reader has finished a case study, what should they do next?

- Discuss the post on a relevant thread in the forum?
- Learn how to do the things they read about in the case study?
- Share with friends?

Could probably be embedded in text of case study or, for a more generic call to action, added to template file: 

https://github.com/frictionlessdata/frictionlessdata.io/blob/gh-pages/_layouts/case_study.html

**Comment by pwalsh** [comment]
+100 on any solution here. Ideally, the discussion thread on forum

**Comment by danfowler** [comment]
This is resolved by adding the forum link to the template: https://github.com/frictionlessdata/frictionlessdata.io/blob/master/_layouts/case_study.html#L43

We can just make sure we carry forward the process of creating a forum post for this type of content and translate the layout faithfully.
