### ISSUE TITLE
Fix the "edit on github" button

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/website-old#110]
On every page there is a right hand menu with a page icon on it. One of the options, titled "edit on github", links to a 404 error on Github.

I speculate the reason might be because this link is generated by a script and Github has changed the URL patterns since the site's theme was developed.

**Comment by augusto-herrmann** [comment]
After looking into it, I found out that the [link in _includes/page-tools.html](https://github.com/frictionlessdata/frictionlessdata.io/blob/master/_includes/page-tools.html#L37) points to a non-existent "gh-pages" branch. To fix it, the link should point to an existing branch (master?).

**Comment by danfowler** [comment]
Thanks @augusto-herrmann for fixing!  I had changed the default branch for this site from `gh-pages` to `master`.  Unintended consequences!
