### ISSUE TITLE
Frictionless Data on OpenML?

### ISSUE THREAD

**Issue by HeidiSeibold** [frictionlessdata/website-old#139]
We are thinking about using your data structures for OpenML.org, an online platform for open machine learning.

We have a workshop in October and I was wondering if any of you would be interested in coming to Leiden and join us.
http://hackathon.openml.org/

Sorry for misusing the issues :cake:

**Comment by pwalsh** [comment]
Hi @HeidiSeibold ! Super interested. Can you write to me at paul.walsh@okfn.org

**Comment by pwalsh** [comment]
(and closing this issue, as we will pick up by email.)
