### ISSUE TITLE
Add a table of contents to the pattern page

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/website-old#146]
Add a table of contents to the [pattern page](http://frictionlessdata.io/specs/patterns/) to allow readers to jump to the pattern of interest. 

Similar to toc used on http://frictionlessdata.io/specs/table-schema/

**Comment by Stephen-Gates** [comment]
Whoops, this may be in the wrong repo given the patterns pages in over at https://github.com/frictionlessdata/specs/blob/master/content/patterns/contents.lr

**Comment by serahkiburu** [comment]
Finally got round to fixing this, @Stephen-Gates. Should be good now.

**Comment by Stephen-Gates** [comment]
@serahrono thanks but I guess what I was hoping for was to be able to navigate down to individual patterns using the ToC like on other spec pages

**Comment by serahkiburu** [comment]
@Stephen-Gates I reckon you should be able to, see screen grab below
<img width="267" alt="patterns-screengrab" src="https://user-images.githubusercontent.com/4550385/35139782-5ac77de0-fcfd-11e7-956c-76912fdbc755.png">

**Comment by Stephen-Gates** [comment]
Perfect!
:tada:
