### ISSUE TITLE
Point location data 7 not GeoJSON

### ISSUE THREAD

**Issue by stevage** [frictionlessdata/website-old#147]
Sorry for this nitpick, but example 7 of the really nicely done [point-location-data](http://frictionlessdata.io/guides/point-location-data/) page (#130) gives this as an example of GeoJSON in CSV:

>`Dalby | {"lon":151.2660, "lat": -27.1944}`

But that's not GeoJSON. If the field is just the geometry/coordinates bit it would be:

`Dalby | [151.2660,-27.1994]`

Or if the whole geometry bit:

`Dalby | {"type":"Point","coordinates":[151.2660,-27.1994]}`

Or if the whole GeoJSON...no let's not go there :)

**Comment by Stephen-Gates** [comment]
Thanks @stevage 

The offending line is https://github.com/frictionlessdata/website/blob/master/content/guides/point-location-data/contents.lr#L349 

Interested to hear from others what the intent of the [specification](http://frictionlessdata.io/specs/table-schema/#geojson) is?

**Comment by roll** [comment]
Interesting - section number 7 is about `geojson` but example is for `geopoint`.

**Comment by Stephen-Gates** [comment]
@roll do you agree that the correct example should be:

`Dalby | {"type":"Point","coordinates":[151.2660,-27.1994]}` ?

**Comment by roll** [comment]
@Stephen-Gates 
I agree.
