### ISSUE TITLE
rebuild website to publish the updated data package version pattern

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/website-old#167]
Please manually rebuild the website (because https://github.com/frictionlessdata/specs/issues/589 isn't implemented) to publish the updated data package version pattern https://github.com/frictionlessdata/specs/pull/592

**Comment by Stephen-Gates** [comment]
thanks @roll

**Comment by roll** [comment]
@Stephen-Gates
Thanks for the heads-up!
