### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by johanricher** [frictionlessdata/website-old#178]
I'd love to translate to French a part or the whole of the website (starting with the Field Guide). Can I contribute in a way that will be also available to visitors of frictionlessdata.io or should I fork the website to publish my translation elsewhere? If so, what's the licence on the content of the website?

**Comment by serahkiburu** [comment]
Hey @johanricher, as I said on Gitter, this is exciting for us, thank you! I'm currently preparing a guide to contributing translations, and should be able to reference it here in the next day or so

**Comment by serahkiburu** [comment]
Hey @johanricher, here you go https://github.com/frictionlessdata/website#contributing-translations

**Comment by johanricher** [comment]
Neat, thank you!
