### ISSUE TITLE
Feedback for Quick start in Python page

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/website-old#19]
@danfowler I think it provides a good overview, just some comments:
- Storage libraries names are wrong: `pip install jsontableschema_sql` -> `pip install jsontableschema-sql`. Same for BigQuery.
- Badly formatted link: `For more information on which fields are supported, see [the full Data Package standard][dp-spec].`
- I was surprised to see how the guide jumped straight from checking the metadata to store the data on an external backend. My first though was how do I see the actual data on the Data Package object? I think it's worth having a section between "Reading basic metadata" and "Loading into an SQL database" named "Reading the data" or something which shows an example like:

```
print [e['name'] for e in dp.resources[0].data if int(e['atomic number']) < 10]
[u'Hydrogen', u'Helium', u'Lithium', u'Beryllium', u'Boron', u'Carbon', u'Nitrogen', u'Oxygen', u'Fluorine']
```

And also mentions any other form of accessing the data directly on python (like lazily with `iter`)

**Comment by danfowler** [comment]
Thanks @amercader.  I didn't notice that the library names were autocorrecting themselves 👍. Fixed.

Really great suggestions.  I'll add a "Reading the data" section.  Given https://github.com/frictionlessdata/datapackage-py/issues/82, I'll probably do what @vitorbaptista does in the [README.md](https://github.com/frictionlessdata/datapackage-py/blob/master/README.md) and cast the values myself for a quick example.  

I'm also wondering about moving the BigQuery and RedShift sections out to a different guide as they seem a bit too specific and less "Hello World".

**Comment by amercader** [comment]
Yeah, BigQuery and RedShift don't sound like "Quick Start" to me :) Just mention there are other backends available and link to a separate page.

**Comment by rufuspollock** [comment]
@amercader @danfowler for now I would just keep this all in one and i want to minimize refactoring and focus on getting content correct and all-in-one is easier. I also note that originally this guide was called "Using Data Packags in Python" which may have been a bit more accurate ;-)

**Comment by danfowler** [comment]
Added a Reading Data section based on @amercader suggestion: http://frictionlessdata.io/guides/using-data-packages-in-python/#reading-data
