### ISSUE TITLE
Broken link on fellows.frictionlessdata.io

### ISSUE THREAD

**Issue by glgoose** [frictionlessdata/website-old#198]
a[href] within a[href] so link text 'forum' not showing properly and html tags showing on page

```html
<p>For more questions on the Fellows Programme, speak directly to us on our &lt;a href="
<a href="https://discuss.okfn.org/c/frictionless-data">https://discuss.okfn.org/c/frictionless-data</a>
" target=_blank&gt;forum&lt;/a&gt;, or email us at frictionlessdata@okfn.org.</p>
```
https://fellows.frictionlessdata.io/

**Comment by lwinfree** [comment]
thanks @glgoose for letting us know! It will be fixed soon. Here is the repo for the fellows website FYI: https://github.com/frictionlessdata/fellows
