### ISSUE TITLE
Tutorial: How to write a Tutorial ...

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#42]
_From @rgrp on May 6, 2016 11:33_
- [ ] Layout and style
  - [ ] Examples to look at
- [ ] Bounties

Cf the #234 (developer guide)

See also https://www.digitalocean.com/community/get-paid-to-write

_Copied from original issue: frictionlessdata/project#247_

**Comment by danfowler** [comment]
Not sure there's anything specific to Frictionless Data the way this issue is written, but the original intention as I recall was to provide a way to onboard people wanting to contribute to the project.  

Users with a basic familiarity of Data Packages could contribute tutorials in their language or platform of choice.

This is fine idea but seems somewhat low priority at this point.  It will ultimately be driven by how people actually use the tools.  I move to close.

**Comment by jobarratt** [comment]
Agreed this can be closed

**Comment by Stephen-Gates** [comment]
Suggest this might be helpful given [the number of tutorials that need to be written](https://github.com/frictionlessdata/frictionlessdata.io/issues/42). I'd be keen to contribute if a template was provided. In the absence of a template, [I made this tutorial up](https://docs.google.com/document/d/1pmA60QEHzUEIk5CEBUrZzMyTbeRGC5fgRpWuHNlyw_M/edit#heading=h.2i0jf2tv286r) - (thanks for the comments Dan).

**Comment by rufuspollock** [comment]
@Stephen-Gates please contribute a template - that would be awesome!

**Comment by jobarratt** [comment]
Thank you so much for this @Stephen-Gates it's really great

**Comment by jobarratt** [comment]
Added to the site. Thank you again @Stephen-Gates 

http://frictionlessdata.io/guides/tutorial-template/
