### ISSUE TITLE
Tutorial: Import Data Package into SQL database

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#47]
_From @danfowler on April 30, 2016 11:20_

This can be really simple and largely point into other tutorials e.g.
- [x] About Tabular Data Package ...
- [x] Python option with python lib #221 
- [ ] "Raw" options - example python scripts showing how simple this is (inline with gist-it)
- [ ] datapak examples (?)

_Copied from original issue: frictionlessdata/project#227_

**Comment by pwalsh** [comment]
What we have seems enough right now
