### ISSUE TITLE
/tools/ page

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website-old#5]
- [x] Migrate current data.okfn.org/tools with minor refactoring
- [ ] <del>Short summary about why tools are essential</del> (?)
- [x] Key online services that you an use (e.g. create, view, validate, validate data)
- [x] Guides - using Data Packages with ...
- [x] Tool catalog - long list. Need to add:
  - Language or Platform
  - Organisation

**Comment by rufuspollock** [comment]
@danfowler if we could add the columns to the tools list and display that, this would be done 😄  - could you take that on (and estimate that).

**Comment by danfowler** [comment]
@rgrp the tools catalog already has Language and Maintainer columns

**Comment by rufuspollock** [comment]
FIXED.

@danfowler yes! I think i was starting a list but not sure what else I wanted other than e.g. "Platform" (e.g. "BigQuery"). I think we may want a separate column for that as that is what many users will care about. That said, right now, that can be a new issue or just left!
