### ISSUE TITLE
Example - House prices regressed on long interest rate and GDP (and population)

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#53]
_From @rgrp on April 6, 2013 15:40_
- R example
- (Maybe we do in other languages too later ...)

_What does it demonstrate: quickly getting data and using it together_
## Required data
- [x] House price data - http://data.okfn.org/data/house-prices-uk
- [x] UK Long interest rate - http://data.okfn.org/data/bond-yields-uk-10y
- [x] UK GDP - http://data.okfn.org/data/gdp-uk

Do we need this quarterly?
## Why this analysis
- People are interested in house prices - why do they go up and down
- Classic explanation is other economic variables e.g. demand (GDP, population and interest rate (mortgages)), supply (housing stock). Here will just use demand variables and see what we find.

_Copied from original issue: frictionlessdata/project#32_

**Comment by danfowler** [comment]
_From @rgrp on April 7, 2013 14:22_

@mk270 ok all the data is there. Let me know how this is going :-)

**Comment by danfowler** [comment]
_From @rgrp on July 7, 2013 16:57_

Not a regression but a nice example of merging two inflation + house prices using data packages: http://explorer.okfnlabs.org/#rgrp/e3e0b0f18dfe151f9f7e + post http://okfnlabs.org/blog/2013/03/18/progress-with-data-explorer.html

**Comment by pwalsh** [comment]
DONE
