### ISSUE TITLE
Move data.okfn.org/tools/* to frictionlessdata.io

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#56]
_From @rgrp on June 17, 2016 11:46_

Split out from #206 
- [ ] Move data.okfn.org/tools/view to viewer.frictionlessdata.io
  - [ ] implement redirect
- [ ] Move data.okfn.org/tools/validate to validate.frictionlessdata.io
  - [ ] implement redirect
- [ ] Redirect data.okfn.org/tools -> fd.io/tools
- [ ] Redirect data.okfn.org/create -> datapackagist.okfnlabs.org 

_Copied from original issue: frictionlessdata/project#261_

**Comment by danfowler** [comment]
per @pwalsh datapackagist.okfnlabs.org is best positioned to replace old validator

**Comment by pwalsh** [comment]
WONTFIX
