### ISSUE TITLE
Refactor /tools

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#71]
A small refactor could make this page a lot more readable.  Regardless of when we do a full redesign, I want to do this @jobarratt before/when we launch Tool Fund, as it would be good to have this in better shape so that people don't get confused about what is and isn't currently out there.  This could serve as inspiration: https://www.quandl.com/tools/full-list

~~- [ ] Move the CSV to a Jekyll collection~~
~~- [ ] Use logos where relevant for programming languages and platforms~~
~~- [ ] Provide more detail on what each tool does and how it fits into the ecosystem~~
~~- [ ] Remove Table of Contents~~
- [x] Add a where to find Data Packages section
- [x] Link to Tool Fund website (when ready)

Add these tools:

- [x] New Excel integrations (e.g. Metatab, datapackage-m)
- [x] Tools like Comma Chameleon, SmartCSV.fx
- [x] Octopub
- [x] CKAN
- [x] Data Retriever

**Comment by danfowler** [comment]
@roll @smth @jobarratt @pwalsh I came across this which could serve as inspiration: https://www.quandl.com/tools/full-list

**Comment by jobarratt** [comment]
@danfowler i think this is a great and very useful idea. But i don't want to delay the launch of the Tool fund too long. if at all. Can you estimate the time it is going to take in Trello. Ill decide whether we hold off the launch when i have a clear idea of when you will be able to do this. Maybe we do when both in London.

**Comment by pwalsh** [comment]
I don't think tool fund should depend on this at all.

**Comment by danfowler** [comment]
@jobarratt @pwalsh I also don't think the Tool Fund should be dependent on this, but I do think it would be helpful and necessary to update.

**Comment by rufuspollock** [comment]
Big 👍  on updating. I had to go and edit this directly this morning when i wanted to link from reddit as content was out of date.

Even if we don't do all of this, just half a day of tidying would make a real difference.

**Comment by danfowler** [comment]
OK, not too much in terms of visual flourish, but I have updated with a simple Markdown document of the range of tools, integrations, platforms, and representations.  Plus a link to the Tool Fund.

https://github.com/frictionlessdata/frictionlessdata.io/pull/118
