### ISSUE TITLE
Add University of Cambridge logo to Partners page

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/website-old#72]
In the usual doc

**Comment by danfowler** [comment]
@jobarratt I considered this and hesitated because of language on Cambridge site: https://www.cam.ac.uk/brand-resources/about-the-logo

> As a valuable asset the Logo is very much in demand by those not entitled to use it. 
> 
> For this reason both the logo and coat of arms are registered trademarks. We have strict control processes in place for when the logo may, and may not, be used, as well as how it should be used. These are essential in order to prevent revocation of the trademarks, so it is important that you follow the guidance provided on this website.

**Comment by jobarratt** [comment]
I would be inclined to go ahead here. These guidelines are for print in any case, and the logo is correct.
