### ISSUE TITLE
Principles page

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website-old#74]
Old data.okfn.org listed a set of principles behind our approach. Useful to have these somewhere - perhaps on the "about" page or even on `/principles/`.

Useful to have up as i want to point people to them ;-)

Here's the old data.okfn.org front page (principles are half-way down): http://web.archive.org/web/20160422020739/http://data.okfn.org/

**Comment by danfowler** [comment]
Duplicate of #94
