### ISSUE TITLE
Wrong locations for tools

### ISSUE THREAD

**Issue by enyst** [frictionlessdata/website-old#76]
The file /guides/publish/faq/index.md, section Validate and preview your Data Package, refers to two tools and links to them, but the links lead nowhere at this time.

The tool referred by the second link is probably now this one:
http://data.okfn.org/tools/view

I'm not sure where is the first tool,  perhaps it's easy to spot but I'm on mobile.

**Comment by danfowler** [comment]
Hi thanks for pointing this out! /tools/ is due for a bit of an overhaul.  I can make the fixes 👍 .

**Comment by Stephen-Gates** [comment]
I think the links should be: 
- http://frictionlessdata.io/tools/#validate 
- http://frictionlessdata.io/tools/#view  (which leads to http://data.okfn.org/tools/view)

Current links are missing the #
