### ISSUE TITLE
Add section and system for user-contributed "patterns" (part of /guides/)

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#78]
- Include template
  - What problem is pattern attempting to address?
  - What version of Data Package specifications does this pattern work for?
  - Why is this a "pattern" and not part of the spec?
  - Examples
- Probably uses Jekyll "Collections": https://jekyllrb.com/docs/collections/

e.g. https://github.com/frictionlessdata/specs/issues/281#issuecomment-241326658

**Comment by rufuspollock** [comment]
Could also go on specs site maybe ...

**Comment by danfowler** [comment]
Yeah, I debated whether to post it here or there, but decided on here to draw some difference between official specs and patterns of use.

**Comment by pwalsh** [comment]
WONTFIX. Issue tracker is the MVP for this. If need is overwhelming, we could formalise it otherwise.
