### ISSUE TITLE
/data-packages/

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website-old#9]
- [x] move `/standards/` => `/data-packages/`
  - Why? Because all the standards / spec stuff **is** about data package and this is much conceptually accurate plus better link naming for SEO
- [ ] redo page to be like front page _but_ about data packages (??)
  - later we should replace the image and not reuse front page image
- [ ] Draw some decent diagrams - see #8 for diagram ideas
  - Current diagram is pretty poor
  - Suggest at least one lego diagram + the general diagram about separation of concerns (though not sure that is super clear and maybe should be in benefits section here or elsewhere)
- [ ] Subpages
  - [ ] specs
  - [ ] profiles

Notes
- Make JTS more prominent e.g. /data-packages/json-table-schema/

Asides:
- [ ] think about about where specs / standards go - see https://github.com/frictionlessdata/ideas/issues/242

**Comment by rufuspollock** [comment]
Newer, nicer diagram done as part of slide deck for CSV Conf. Want to extract this and insert.

Specs will probably not be subpages but subsite as per: https://github.com/frictionlessdata/ideas/issues/242

**Comment by rufuspollock** [comment]
@roll can we not go about assigning people here - this should be part of the sprint planning we did yesterday. I am not assigned on this item. Please liase with me before we do assignments etc 😄

**Comment by roll** [comment]
Oh, @rgrp, no problem. My mistake was to make this repo as base for all low-level tech stuff. Now l see it mess with your current methodolody so l will rebase waffle board to some of main tech repos like `datapackage-py` with excluded:
- `ideas`
- `frictionlessdata.io` 

PS.
Sorry wrong button from the phone (close/reopen) also message is updated.

**Comment by roll** [comment]
@rgrp It's back to normal - https://waffle.io/frictionlessdata/frictionlessdata.io (also I've removed labels added by waffle). Sorry for the confusion.

**Comment by pwalsh** [comment]
Merged with https://github.com/frictionlessdata/frictionlessdata.io/issues/129
