### ISSUE TITLE
Create a Data Package (datapackage.json) online (generic - no specific tool)

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#90]
_From @danfowler on April 30, 2016 11:5_

Create a Data Package (datapackage.json) online (generic - no specific tool)
- [ ] Reinstate datapackage-init-js demo
- [ ] Walkthrough of Datapackagist

Current issues with DataPackagist
- [ ] UX is confusing in many ways
- [ ] Very complex codebase

_Copied from original issue: frictionlessdata/project#223_

**Comment by Stephen-Gates** [comment]
Can this be closed thanks to https://create.frictionlessdata.io/ ?
