### ISSUE TITLE
'Add user story' button to the homepage

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/website-old#91]
'Add user story' button to the homepage and submit to the trello board via google form.

**Comment by danfowler** [comment]
@jobarratt @roll I'm not sure how the OpenTrials approach works, but I didn't see this as submitting directly to Trello.

**Comment by roll** [comment]
@danfowler 
I suppose it just sends email via google form - http://explorer.opentrials.net/ - see right bottom corner.

**Comment by pwalsh** [comment]
WONTFIX
