### ISSUE TITLE
Frictionless Data principles and summary about on site (front page?)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website-old#94]
The old site had a set of principles on the front page. these no longer appear on the current site and they were useful and important - they articulate for people the essence of our approach and how it might differ from other ones.

See: http://web.archive.org/web/20160422020739/http://data.okfn.org/
### Principles

1 Focused

We have a sharp focus on one part of the data chain, one specific feature – packaging – and a few specific types of data (e.g. tabular).

2 Web Oriented

We build build for the web using formats that are web "native" such as JSON, work naturally with HTTP such as plain text CSVs (which stream).

3 Distributed

Distributed rather than centralized: we design for a distributed ecosystem with no centralized, single point of failure or dependence.

4 Open

Anyone should be able to freely and openly use and reuse what we build. Our community is open to everyone.

5 Existing Tooling

Integrate as easily as possible with existing tools both by building integrations and designing for direct use – for example we like CSV because everyone has a tool that can access CSV.

6 Simple, Lightweight

Add the minimum, do the least required, keep it simple. For example, use the most basic formats, require only the most essential metadata, data should have nothing extraneous.

**Here's a slightly improved rewrite**

1 Focused

When discussing how we should do something have a sharp focus on one part of the data chain, one specific feature – e.g. packaging – and/or a few specific types of data (e.g. tabular).

_Comment:  data is often too broad a category for answers other than at the most general level ("provide metadata", have good quality data). You need to get specific to get useful answers._

2 Web Oriented

Build build for the web using formats that are web "native" such as JSON, work naturally with HTTP such as plain text CSVs (which stream).

_Comment: you could obviously mention RDF here which was definitely built for the web. But see simplicity principle below._

3 Distributed

Be distributed rather than centralized: design for a distributed ecosystem with no centralized, single point of failure or dependence.

4 Open

Anyone should be able to freely and openly use and reuse what is built. The community should be open to everyone.

5 Existing Tooling

Integrate with existing tools both by building integrations and designing for direct use – for example CSV is great because everyone has a tool that can access CSV.

6 Simplicity

Keep it simple and make things easy to learn and use. Add the minimum and do the least required. Concretely this means using simple formats, keeping metadata lightweight, and data specs simple.
### About

_I imagine this could be tightened substantially_

Our work is focused around "Data Packages", lightweight "packaging" format for data that provide a basis for convenient publication, installation and management of datasets.

They aim to deliver functionality similar to "packaging" in software and "containerization" in shipping: a simple wrapper and basic structure for transportation of data that significantly reduces the friction in data sharing and integration, supports automation and does this without imposing major changes on the underlying data being packaged.

The specification is now fairly mature and has a growing set of tooling around it. There is a particular focus on tabular data but any kind of data can be "packaged". Because of its lightweight and simple nature it is easy to adopt both for data publishers, data users and data tool makers.

_Tighter version_

We provide a simple wrapper and basic structure for transportation of data that significantly reduces the friction in data sharing and integration, supports automation and does this without imposing major changes on the underlying data being packaged. You can think of it as analogous to "packaging" in software and "containerization" in shipping but for data. 

Specifically we provide lightweight specification for data packages together with a rich set of tooling  and integrations. We focus on tabular data but any kind of data can be "packaged". Its lightweight and simple nature it is easy to adopt both for data publishers, data users and data tool makers.

**Comment by rufuspollock** [comment]
Actually maybe a simple `/principles/` page would be nice and easy to link to ;-)

**Comment by roll** [comment]
I remember it. It was very helpful when I've read about FD first time.

**Comment by danfowler** [comment]
Thanks @rgrp @roll I think we can bring these back in.  I'd like to keep as few pages as possible, so I would probably insert into /about/#principles (maybe even redirect /principles/ to /about/#principles).

**Comment by danfowler** [comment]
@rufuspollock @roll I condensed the principles even more.  Let me know what you think: http://frictionlessdata.io/about/#principles
