### ISSUE TITLE
Specs page design

### ISSUE THREAD

**Issue by serahkiburu** [frictionlessdata/website-old#95]
http://specs.frictionlessdata.io looks different from the rest of the pages on frictionlessdata.io. By design or should we consider updating?

**Comment by danfowler** [comment]
@callmealien http://specs.frictionlessdata.io has a different design due to history/expedience.  The specs page was originally a different site altogether with lots of other specs (cf: http://specs.okfnlabs.org/).  We should definitely have a unified design for both.

**Comment by pwalsh** [comment]
Merged with https://github.com/frictionlessdata/frictionlessdata.io/issues/129
